# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Numerika
tagline:          'štvrtok 7:30'
description:      'Stránky k cvičeniam z predmetu Numerické metódy (NME1) na FJFI ČVUT - cvičenie štvrtok 7:30'
url:              
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

