# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Numerika
tagline:          'štvrtok 7:30'
description:      'Stránky k cvičeniam z predmetu Numerické metódy (NME1) na FJFI ČVUT'
url:              
baseurl:          /

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed


author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

